CREATE EXTERNAL TABLE `biz_data.contracts`(
account_id string,
asset_id string,
asset_type string,
auto_renewal string,
auto_renewal_status string,
billing_period string,
bop_code string,
broker_plan_affiliation string,
cancellation_date timestamp,
contract_number string,
contract_term string,
contracted_amlc string,
contracted_impressions int,
created_date timestamp,
credit_amount double,
credit_status string,
daily_contract_value double,
daily_rate double,
daily_rate_on_asset double,
days double,
description string,
discount_type string,
email string,
end_date timestamp,
est_tax double,
est_total_tax double,
expired_date timestamp,
ext_days int,
extended_end_date timestamp,
extension_type string,
free_extension string,
fulfilled_zip_list string,
fulfillment_required string,
fulfillment_status string,
fulfillment_status_notes string,
fullfil_to_account_cdh_party_id string,
fullfil_to_account_id string,
fullfil_to_account_mls_set_id string,
fullfil_to_account_name string,
fullfil_to_account_type string,
hlc double,
hlc_override double,
inventory_reference_id string,
inventory_status string,
is_competitor_product string,
is_deleted string,
is_inactive string,
land_amlc string,
land_amlc_override string,
last_modified_date timestamp,
last_referenced_date timestamp,
lead_type string,
legacy_product string,
license_id string,
license_keywords string,
license_level string,
license_name string,
license_primary_city string,
license_sale_type string,
license_state string,
license_tier string,
license_tier_range string,
line_type string,
list_price string,
manual_discount double,
manual_discount_type string,
manual_override_amount string,
manual_price_override double,
market string,
market_code string,
market_tier string,
market_zip string,
mls_set string,
mls_set_id string,
mls_type string,
msa_tier string,
name string,
nar_membership string,
net_monthly_price double,
net_price double,
original_total_net_contract_value string,
parent_asset_id string,
product2id string,
product_code string,
product_type string,
promotion_amount double,
promotion_code double,
purchase_date timestamp,
quantity string,
rate_card string,
remaining_amount double,
renewal_status string,
siebel_asset_id string,
siebel_order_id string,
sold_to_account_cdh_party_id string,
sold_to_account_id string,
sold_to_account_mls_set_id string,
sold_to_account_name string,
sold_to_account_type string,
start_date timestamp,
status string,
systemmodstamp timestamp,
team string,
term_end_date timestamp,
term_start_date timestamp,
total_credit string,
total_discount double,
total_discount_percent double,
total_list_price double,
total_net double,
total_net_monthly string,
total_net_price string,
total_price_withtax double,
ultimate_parent_asset_id string,
ultimate_parent_asset_name string
)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://move-dataeng-cntr-dev/contracts/businessdata/sfdc_contracts'
TBLPROPERTIES (
  'PARQUET.COMPRESS'='SNAPPY',
  'transient_lastDdlTime'='1519870171')