select
absentee_indicator_code,
apn_sequence_number,
apn_unformatted,
batch_id,
batch_seq,
book_page,
cash_mortgage_purchase_code,
construction_loan_flag,
day,
deed_sec_cat_codes,
document_number,
document_type_code,
equity_flag_code,
etl_create_date,
etl_datatype_processed_ind,
etl_invalid_criticality_ind,
etl_invalid_details,
etl_last_update_timestamp,
etl_partition_key_timestamp,
etl_rd_arrival_day,
etl_rd_arrival_hour,
etl_rd_arrival_month,
etl_rd_arrival_year,
etl_source_filename,
etl_source_partition_timestamp,
etl_ztg_id,
filler03,
fips_code,
forclosure_code,
hour,
inter_family_flag,
case when latitude <> '' then round(cast(latitude as integer)*1.0 / 1000000, 6) else '' end latitude,
lender_address,
lender_city,
lender_company_code,
lender_first_name,
lender_last_name,
lender_state,
lender_zipcode,
case when substring(longitude, 9, 1) = '}' then round(cast(concat(substring(longitude, 1, 8), '0') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'J' then round(cast(concat(substring(longitude, 1, 8), '1') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'K' then round(cast(concat(substring(longitude, 1, 8), '2') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'L' then round(cast(concat(substring(longitude, 1, 8), '3') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'M' then round(cast(concat(substring(longitude, 1, 8), '4') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'N' then round(cast(concat(substring(longitude, 1, 8), '5') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'O' then round(cast(concat(substring(longitude, 1, 8), '6') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'P' then round(cast(concat(substring(longitude, 1, 8), '7') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'Q' then round(cast(concat(substring(longitude, 1, 8), '8') as integer)*-1.0 / 1000000, 6)
when substring(longitude, 9, 1) = 'R' then round(cast(concat(substring(longitude, 1, 8), '9') as integer)*-1.0 / 1000000, 6) else '' end longitude,
mail_apartment_unit_number,
mail_carrier_route,
mail_city,
mail_house_number,
mail_house_number_prefix,
mail_house_number_suffix,
mail_mode,
mail_quadrant,
mail_state,
mail_street_direction,
mail_street_name,
mail_zipcode,
month,
mortgage_amount,
mortgage_assumption_amount,
mortgage_book_page,
mortgage_date,
mortgage_deed_type_code,
mortgage_document_number,
mortgage_due_date,
mortgage_interest_rate,
mortgage_interest_rate_type_code,
mortgage_loan_type_code,
mortgage_sequence_number,
mortgage_term,
mortgage_term_code,
mtg_sec_cat_codes,
multi_apn_flag,
owner_buyer_1_first_name_m_i,
owner_buyer_1_last_name,
owner_buyer_2_first_name_m_i,
owner_buyer_2_last_name,
owner_co_name,
owner_corporate_indicator_flag,
owner_etal_indicator_code,
owner_ownership_rights_code,
owner_relationship_type_code,
ownership_transfer_percentage,
partial_interest_indicator_flag,
pcl_id_iris_frmtd,
pending_record_indicator,
pri_cat_code,
private_party_lender_flag,
regexp_replace(ltrim(regexp_replace(property_apartment_unit_number,'0',' ')),' ','0') property_apartment_unit_number,
property_carrier_route,
property_city,
property_direction,
regexp_replace(ltrim(regexp_replace(property_house_number,'0',' ')),' ','0') property_house_number,
property_house_number_prefix,
property_house_number_suffix,
property_indicator_code,
property_mode,
property_quadrant,
property_state,
regexp_replace(ltrim(regexp_replace(property_street_name,'0',' ')),' ','0') property_street_name,
substring(property_zipcode, 1, 5) property_zipcode,
record_type_code,
recording_date,
refi_flag_code,
resale_new_construction_code,
residential_model_indicator_flag,
sale_amount,
sale_code,
sale_date,
seller_carry_back_flag,
seller_first_name,
seller_last_name,
seller_naem_plaintiff_2,
seller_name_plaintiff_1,
title_company_code,
title_company_name,
transaction_type_code,
case when cast(sale_date as integer) > 0 then sale_date
when cast(sale_date as integer) = 0  and cast(recording_date as integer) > 0 then recording_date
else '99991231' end transfer_date,
universal_land_use_code,
year
from
corelogic_deed cl