
CREATE EXTERNAL TABLE `newhomes_sub_division`(
am_plan_record_status string,
bdx_plan_id string,
created_by string,
created_date timestamp,
date_is_live timestamp,
effective_from timestamp,
effective_to timestamp,
is_deleted string,
master_plan_id string,
master_sub_division_id string,
modified_by string,
modified_date timestamp,
photo_count string,
plan_adr_city string,
plan_adr_country string,
plan_adr_county string,
plan_adr_geo_lat string,
plan_adr_geo_long string,
plan_adr_out_of_community string,
plan_adr_state string,
plan_adr_street1 string,
plan_adr_street2 string,
plan_adr_zip string,
plan_amen_fire_places string,
plan_amen_vaulted_ceilings string,
plan_amen_walkin_closets string,
plan_basement string,
plan_base_price string,
plan_base_price_excludes_land string,
plan_base_sqft string,
plan_baths string,
plan_bed_rooms string,
plan_bonus_room string,
plan_desc string,
plan_dim_key string,
plan_dining_areas string,
plan_dining_room string,
plan_envision_design_center string,
plan_family_room string,
plan_game_room string,
plan_garage string,
plan_garage_entry string,
plan_guest_room string,
plan_half_baths string,
plan_hot_home string,
plan_hot_home_desc string,
plan_hot_home_title string,
plan_img_viewer string,
plan_img_virtual_tour string,
plan_living_area string,
plan_living_area_type string,
plan_living_room string,
plan_loft string,
plan_marketing_head_line string,
plan_master_bed_location string,
plan_media_room string,
plan_name string,
plan_not_available string,
plan_number string,
plan_off_room string,
plan_stories string,
plan_study string,
plan_sun_room string,
plan_type string,
plan_web_site string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://move-dataeng-lstp-dev/edw/business-data/newhomes_sub_division'
TBLPROPERTIES (
  'PARQUET.COMPRESS'='SNAPPY',
  'transient_lastDdlTime'='1518805996')
CREATE EXTERNAL TABLE `newhomes_sub_division`(
am_plan_record_status string,
bdx_plan_id string,
created_by string,
created_date timestamp,
date_is_live timestamp,
effective_from timestamp,
effective_to timestamp,
is_deleted string,
master_plan_id string,
master_sub_division_id string,
modified_by string,
modified_date timestamp,
photo_count string,
plan_adr_city string,
plan_adr_country string,
plan_adr_county string,
plan_adr_geo_lat string,
plan_adr_geo_long string,
plan_adr_out_of_community string,
plan_adr_state string,
plan_adr_street1 string,
plan_adr_street2 string,
plan_adr_zip string,
plan_amen_fire_places string,
plan_amen_vaulted_ceilings string,
plan_amen_walkin_closets string,
plan_basement string,
plan_base_price string,
plan_base_price_excludes_land string,
plan_base_sqft string,
plan_baths string,
plan_bed_rooms string,
plan_bonus_room string,
plan_desc string,
plan_dim_key string,
plan_dining_areas string,
plan_dining_room string,
plan_envision_design_center string,
plan_family_room string,
plan_game_room string,
plan_garage string,
plan_garage_entry string,
plan_guest_room string,
plan_half_baths string,
plan_hot_home string,
plan_hot_home_desc string,
plan_hot_home_title string,
plan_img_viewer string,
plan_img_virtual_tour string,
plan_living_area string,
plan_living_area_type string,
plan_living_room string,
plan_loft string,
plan_marketing_head_line string,
plan_master_bed_location string,
plan_media_room string,
plan_name string,
plan_not_available string,
plan_number string,
plan_off_room string,
plan_stories string,
plan_study string,
plan_sun_room string,
plan_type string,
plan_web_site string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://move-dataeng-lstp-dev/edw/business-data/newhomes_sub_division'
TBLPROPERTIES (
  'PARQUET.COMPRESS'='SNAPPY',
  'transient_lastDdlTime'='1518805996')