WITH edw_builders AS
(
select
row_number() OVER (PARTITION BY BuilderId ORDER BY cast(builderdimkey as bigint) DESC) AS row_number_seq,
builderdimkey,
builderid,
isdeleted,
dateislive,
bdxbuilderid,
buildernumber,
brandname,
reportingname,
defaultleadsemail,
defaultleadsemailleadspermessage,
copyleadsemail,
copyleadsemailleadspermessage,
builderwebsite,
brandlogo,
corpid,
corpbuildernumber,
corpstate,
corpname,
corpreportingemail,
sendtocorponly,
ambuilderrecordstatus,
effectivefrom,
effectiveto,
createddate,
createdby,
modifieddate,
modifiedby
from
lstp_edw_pdt__builder_dim
)
SELECT
ambuilderrecordstatus am_builder_record_status ,
bdxbuilderid bdx_builder_id,
brandlogo brand_logo,
brandname brand_name,
builderdimkey builder_dim_key,
builderid builder_id,
buildernumber builder_number,
lower(builderwebsite) builder_website,
lower(copyleadsemail) copy_leads_email,
lower(copyleadsemailleadspermessage) copy_leads_email_leads_per_message,
corpbuildernumber corp_builder_number,
corpid corp_id,
lower(corpname) corp_name,
corpreportingemail corp_reporting_email,
lower(corpstate) corp_state ,
createdby created_by,
cast(substring(createddate,1,23)as timestamp) created_date,
cast(substring(dateislive,1,23)as timestamp) date_is_live,
defaultleadsemail default_leads_email,
lower(defaultleadsemailleadspermessage) default_leads_email_leads_per_message,
cast(substring(effectivefrom,1,23)as timestamp) effective_from,
cast(substring(effectiveto,1,23)as timestamp) effective_to,
CASE WHEN isdeleted = '1' THEN 'y' else 'n' END is_deleted,
modifiedby modified_by,
cast(substring(modifieddate,1,23)as timestamp) modified_date,
lower(reportingname) reporting_name,
CASE WHEN sendtocorponly = '1' THEN 'y' else 'n' END send_to_corp_only
FROM edw_builders
WHERE row_number_seq = 1
