WITH edw_listings AS
(
select
row_number() OVER (PARTITION BY listingdimkey ORDER BY modified_created_datetime DESC, effective_to_datetime ASC ) AS row_number_seq,
isaolsyndication,
masterplanid,
specid,
listingnumberofbedrooms,
listingaddress,
dapendingflag,
listingpricereduceddate,
buyeragentsourcealiasid,
listingsourcealiasid,
isvirtualtour,
buyerofficesourcealiasid,
ischoiceenabled,
listingsquarefeet,
hascobroke,
listingid,
openhouseenddate,
listingcoofficesourcealiasid,
listingofficesourcealiasid,
listingcounty,
listingenddate,
listingoriginalprice,
createdby,
ispricedropped,
producttypedimkey,
buyeragentofficedatasourceid,
listingcoagentsourcealiasid,
listingagentsourcealiasid,
listingprovider,
listingstatus,
systemcreationdate,
listingstatuschangeddate,
listingnumberofbathrooms,
listingpostalcode,
listingrentalprice,
listingcity,
listingcoagentofficedatasourceid,
listingpriceincreaseddate,
listinggeoapproximation,
newconstructionflag,
listingsolddate,
listingphotocount,
modifiedby,
rowversion,
listingrawstatus,
createddate,
listinglotsquarefeet,
dapendingdate,
modifieddate,
isvideo,
listingpercentagecompleteness,
effectivefrom,
listingsoldprice,
buyercoofficesourcealiasid,
ispriceincreased,
listingagentofficedatasourceid,
fulfillmentgroupbitmask,
listingphotourl,
hascobrokephone,
listingtype,
listingstate,
headline,
specialmessage,
isrental,
listingdatasourceid,
propertydescription,
isrdcsyndication,
isopenhouse,
listingstartdate,
nonmlsflag,
listingdimkey,
listingcountry,
openhousestartdate,
listingcurrentprice,
listingnumberofstories,
isforeclosure,
listingmarketingtype,
effectiveto,
buyercoagentofficedatasourceid,
headline2,
isdisplayed,
udblistingid,
listingstyle,
propertyid,
buyercoagentsourcealiasid,
etl_datatype_processed_ind,
etl_ztg_id,
etl_invalid_details,
etl_rd_arrival_year,
etl_source_partition_timestamp,
etl_partition_key_timestamp,
etl_last_update_timestamp,
etl_rd_arrival_month,
etl_source_filename,
etl_dedupe_md5_checksum,
etl_invalid_criticality_ind,
etl_rd_arrival_hour,
etl_rd_arrival_day,
etl_create_date,
listing_end_datetime,
effective_to_datetime,
created_datetime,
listing_number_of_bathrooms_double,
listing_sold_datetime,
listing_original_price_double,
system_creation_datetime,
listing_lot_square_feet_double,
da_pending_datetime,
effective_from_datetime,
listing_rental_price_double,
listing_square_feet_double,
modified_created_datetime,
listing_status_changed_datetime,
listing_start_datetime,
listing_price_reduced_datetime,
open_house_start_datetime,
open_house_end_datetime,
listing_current_price_double,
listing_price_increased_datetime,
listing_percentage_completeness_double,
listing_sold_price_double,
modified_datetime,
listing_number_of_stories_double
from
lstp_edw_pdt__listing_dim where effective_to_datetime >= '2016-01-01'
and effective_to_datetime < '2017-01-01'
)
SELECT
edw_listings.buyeragentofficedatasourceid buyer_agent_office_data_source_id,
edw_listings.buyeragentsourcealiasid buyer_agent_source_alias_id,
edw_listings.buyercoagentofficedatasourceid buyer_coagent_office_data_source_id,
edw_listings.buyercoagentsourcealiasid buyer_coagent_source_alias_id,
edw_listings.buyercoofficesourcealiasid buyer_cooffice_source_alias_id,
edw_listings.buyerofficesourcealiasid buyer_office_source_alias_id,

edw_listings.createdby created_by,
edw_listings.dapendingflag da_pending_flag,
edw_listings.etl_create_date,
edw_listings.etl_datatype_processed_ind,
edw_listings.etl_dedupe_md5_checksum,
edw_listings.etl_invalid_criticality_ind,
edw_listings.etl_invalid_details,
edw_listings.etl_last_update_timestamp,
edw_listings.etl_partition_key_timestamp,
edw_listings.etl_rd_arrival_day,
edw_listings.etl_rd_arrival_hour,
edw_listings.etl_rd_arrival_month,
edw_listings.etl_rd_arrival_year,
edw_listings.etl_source_filename,
edw_listings.etl_source_partition_timestamp,
edw_listings.etl_ztg_id,
edw_listings.fulfillmentgroupbitmask fulfillment_group_bitmask,
edw_listings.hascobroke has_cobroke,
lower(edw_listings.headline) head_line,
lower(edw_listings.headline2) head_line2,
CASE WHEN edw_listings.ischoiceenabled = '1' THEN 'y' else 'n' END is_choice_enabled,
CASE WHEN edw_listings.isdisplayed = '1' THEN 'y' else 'n' END is_displayed,
CASE WHEN edw_listings.isforeclosure = '1' THEN 'y' else 'n' END is_fore_closure,
CASE WHEN edw_listings.isopenhouse = '1' THEN 'y' else 'n' END is_open_house,
CASE WHEN edw_listings.ispricedropped = '1' THEN 'y' else 'n' END is_price_dropped,
CASE WHEN edw_listings.ispriceincreased = '1' THEN 'y' else 'n' END is_price_increased,
CASE WHEN edw_listings.isrdcsyndication = '1' THEN 'y' else 'n' END is_rdc_syndication,
CASE WHEN edw_listings.isrental = '1' THEN 'y' else 'n' END is_rental,
CASE WHEN edw_listings.isvideo = '1' THEN 'y' else 'n' END is_video,
CASE WHEN edw_listings.isvirtualtour = '1' THEN 'y' else 'n' END is_virtual_tour,

lower(edw_listings.listingaddress) listing_address,
edw_listings.listingagentsourcealiasid listing_agent_mls_id,
upper(CONCAT('A','-',trim(edw_listings.listingagentofficedatasourceid),'-',trim(edw_listings.listingagentsourcealiasid))) listing_agent_mls_set_id,
edw_listings.listingcity listing_city,

edw_listings.listingcoagentofficedatasourceid listing_coagent_office_data_source_id,
edw_listings.listingcoagentsourcealiasid listing_coagent_source_alias_id,
edw_listings.listingcoofficesourcealiasid listing_cooffice_source_alias_id,

edw_listings.listingcountry listing_country,
edw_listings.listingcounty listing_county,
edw_listings.listing_current_price_double listing_current_price,
edw_listings.listingdatasourceid listing_data_source_id,
edw_listings.listingdimkey listing_dim_key,
edw_listings.listingid listing_id,
edw_listings.listing_lot_square_feet_double listing_lot_square_feet,

edw_listings.listingmarketingtype listing_marketing_type,

edw_listings.listing_number_of_bathrooms_double listing_number_of_bath_rooms,
edw_listings.listingnumberofbedrooms listing_number_of_bed_rooms,
edw_listings.listing_number_of_stories_double listing_number_of_stories,
edw_listings.listingofficesourcealiasid listing_office_mls_id,
upper(CONCAT('O','-',trim(edw_listings.listingagentofficedatasourceid),'-',trim(edw_listings.listingofficesourcealiasid))) listing_office_mls_set_id,
edw_listings.listing_original_price_double listing_original_price,
edw_listings.listingphotocount listing_photo_count,
edw_listings.listingphotourl listing_photo_url,
edw_listings.listingpostalcode listing_postal_code,
edw_listings.listingprovider listing_provider,
lower(edw_listings.listingrawstatus) listing_raw_status,
edw_listings.listing_rental_price_double listing_rental_price,
edw_listings.listing_sold_price_double listing_sold_price,
edw_listings.listing_square_feet_double listing_square_feet,
edw_listings.listingstate listing_state,
lower(edw_listings.listingstatus) listing_status,
edw_listings.listingstyle listing_style,
edw_listings.listingtype listing_type,
edw_listings.masterplanid master_plan_id,
edw_listings.listingagentofficedatasourceid mls_id,
edw_listings.listingsourcealiasid mls_property_id,
edw_listings.modifiedby modified_by,
edw_listings.created_datetime mst_created_datetime,
edw_listings.da_pending_datetime mst_da_pending_datetime,
edw_listings.effective_from_datetime mst_effective_from_datetime,
edw_listings.effective_to_datetime mst_effective_to_datetime,
edw_listings.listing_end_datetime mst_listing_end_datetime,
edw_listings.listing_price_increased_datetime mst_listing_price_increased_datetime,
edw_listings.listing_price_reduced_datetime mst_listing_price_reduced_datetime,
edw_listings.listing_sold_datetime mst_listing_sold_datetime,
edw_listings.listing_start_datetime mst_listing_start_datetime,
edw_listings.listing_status_changed_datetime mst_listing_status_changed_datetime,
edw_listings.modified_created_datetime mst_modified_created_datetime,
edw_listings.modified_datetime mst_modified_datetime,
edw_listings.open_house_end_datetime mst_open_house_end_datetime,
edw_listings.open_house_start_datetime mst_open_house_start_datetime,
edw_listings.system_creation_datetime mst_system_creation_datetime,
edw_listings.newconstructionflag new_construction_flag,
edw_listings.nonmlsflag non_mls_flag,
edw_listings.producttypedimkey product_type_dimkey,
edw_listings.propertydescription property_description,
edw_listings.propertyid property_id,
edw_listings.specid spec_id,
edw_listings.specialmessage special_message,
edw_listings.udblistingid udb_listing_id
FROM edw_listings
WHERE edw_listings.row_number_seq = 1
