    select
actualleadreceivercount as actual_lead_receiver_count,
advertiserselectedcount as advertiser_selected_count,
--agentcustomerdimkey as agent_customer_dim_key,
--agentlegacycustid as agent_legacy_cust_id,
--agentofficedimkey as agent_office_dim_key,
agentofficeid as agent_office_party_id,
--agentofficelegacycustid as agent_office_legacy_cust_id,
agentofficesalesforceaccountid as agent_office_salesforce_account_id,
agentofficesiebelacctid as agent_office_siebel_acct_id,
agentcustomerid as agent_party_id,
agentsalesforceaccountid as agent_salesforce_account_id,
bdxplanid as bdx_plan_id,
bdxsubdivisionid as bdx_subdivision_id,
--billablecustomerid as billable_customer_id,
billtoproductdescription as bill_to_product_description,
billtoproductid as bill_to_productid,
billingadvertiserid as billing_advertiser_id,
billingcustomerid as billing_customer_id,
billingsalesforceaccountid as billing_enterprise_account_id,
billinglineitem as billing_line_item,
billingcustid as billing_party_id,
--billingcustomerdimkey as billing_customer_dim_key,
--billinglegacycustid as billing_legacy_cust_id,
billingrefernceid as billing_reference_id,
blockedleadreason as blocked_lead_reason,
bopbillingreferenceid as bop_billing_reference_id,
bopcode as bop_code,
--brokercdhpartyid as broker_cdh_party_id,
--brokercustomerdimkey as broker_customer_dim_key,
case when brokercustomerid='-1' then brokercdhpartyid else brokercustomerid end as broker_party_id,
--brokerlegacycustid as broker_legacy_cust_id,
case when brokersalesforceaccountid like '0%' then brokersalesforceaccountid when brokeracctid like '0%' then brokeracctid else '' end as broker_salesforce_account_id,
case when brokeracctid like '1-%' then brokeracctid when brokersalesforceaccountid like '1-%' then brokersalesforceaccountid else '' end as broker_siebel_account_id,
--callresponsedimkey as call_response_dim_key,
lower(channelclassification) as channel_classification,
--channeldimkey as channel_dim_key,
lower(channelname) as channel_name,
communitydimkey as community_dim_key,
communityid as community_id,
communitymanagmentid as community_management_id,
--conlistingproductrecipientcustcustomerid as con_listing_product_recipient_cust_customer_id,
--conlistingproductrecipientcustdimkey as con_listing_product_recipient_cust_dim_key,
--conlistingproductrecipientcustlegacycustid as con_listing_product_recipient_cust_legacy_cust_id,
--conlistingproductrecipientcustsalesforceaccountid as con_listing_product_recipient_cust_salesforce_account_id,
--connectedagentadvid as connected_agent_adv_id,
--connectedagentcustomerdimkey as connected_agent_customer_dim_key,
--connectedagentcustomerid as connected_agent_customer_id,
--connectedagentcustomerlegacycustid as connected_agent_customer_legacy_cust_id,
--connectedagentcustomersalesforceaccountid as connected_agent_customer_salesforce_account_id,
conproductfullfillmentgroupdimkey as con_product_fullfillment_group_dim_key,
conproductrdcfulfillmentproductname as con_product_rdc_fulfillment_product_name,
--consumerdevicedetailsdimkey as consumer_device_details_dim_key,
--consumerdevicetype as consumer_device_type,
--consumermemberdimkey as consumer_member_dim_key,
--consumeroperatingsystem as consumer_operating_system,
--consumerscreenwidth as consumer_screen_width,
contactaccountid as contact_account_id,
contactemail as consumer_contact_email,
contactfullname as consumer_contact_full_name,
--leadcontactdimkey as lead_contact_dim_key,
lower(leadcontactmethod) as consumer_contact_method,
--leadcontactmethoddimkey as lead_contact_method_dim_key,
lower(leadcontactmethodgroup) as consumer_contact_method_group,
contactphone as consumer_contact_phone,
lower(memberaccountid) as consumer_member_id,
lower(sessionid) as consumer_session_id,
lower(visitorid) as consumer_visitor_id,
createddatetime as created_datetime,
--customerleadtypedimkey as customer_lead_type_dim_key,
--datasourcedimkey as data_source_dim_key,
--datasourceid as data_source_id,
--domaindimkey as domain_dim_key,
domainname as domain_name,
duplicateleadid as duplicate_lead_id,
duration as call_duration,
--etl_create_date,
--etl_datatype_processed_ind,
--etl_dedupe_md5_checksum,
--etl_invalid_criticality_ind,
--etl_partition_key_timestamp,
--etl_rd_arrival_day,
--etl_rd_arrival_hour,
--etl_rd_arrival_month,
--etl_rd_arrival_year,
--etl_source_filename,
--etl_source_partition_timestamp,
etl_unique_lead_id,
etl_ztg_id,
--eventattributesdimkey as event_attributes_dim_key,
--eventattributesgroupbitmask as event_attributes_group_bit_mask,
eventtypedescription as event_type_description,
--eventtypedimkey as event_type_dim_key,
eventtypeid as event_type_id,
--fcma,
--fcmabaths,
--fcmabeds,
--fcmainquirydimkey,
--fcmapricemax,
--fcmapricemin,
--fcmasource,
flexflag as flex_flag,
freeleadreason as free_lead_reason,
--gatewaydimkey as gateway_dim_key,
gatewayname as gateway_name,
case when freelead=1 then 'y' else 'n' end as is_free_lead,
leadadvertiserselectiontype as lead_advertiser_selection_type,
--leadadvertiserselectiontypedimkey as lead_advertiser_selection_type_dim_key,
leadadvertisertype as lead_advertiser_type,
lower(leadcategory) as lead_category,
--leadcategorydimkey as lead_category_dim_key,
lower(leadcategorygroup) as lead_category_group,
lower(leadcategorysemigroup) as lead_category_semi_group,
lower(leadcategorysubgroup) as lead_category_subgroup,
leadcount as lead_count,
leadforid as lead_for_id,
--leadformdimkey as lead_form_dim_key,
leadformname as lead_form_name,
lower(leadid) as lead_id,
leadidxleads as lead_id_xleads,
--leadinquirydimkey as lead_inquiry_dim_key,
leadinquiryemailcopytoself as lead_inquiry_email_copy_to_self,
leadinquiryestimatedtimeframe as lead_inquiry_estimated_timeframe,
leadinquirylistingmlsnumber as lead_inquiry_listing_mls_number,
leadinquirypreferredcontacttime as lead_inquiry_preferred_contact_time,
leadinquirypreferredresponsetime as lead_inquiry_preferred_response_time,
leadinquiryquestionorcomment as lead_inquiry_question_or_comment,
lead_inquiry_rental_moving_datetime,
leadinquiryrentalmovingdatetime as lead_inquiry_rental_moving_datetime_str,
leadinquirysavelisting as lead_inquiry_save_listing,
leadinquirysearchcriteriaaddress as lead_inquiry_search_criteria_address,
leadinquirysearchcriteriacity as lead_inquiry_search_criteria_city,
leadinquirysearchcriteriapostalcode as lead_inquiry_search_criteria_postal_code,
leadinquirysearchcriteriapropertytypes as lead_inquiry_search_criteria_property_types,
leadinquirysearchcriteriastate as lead_inquiry_search_criteria_state,
leadinquirysellbydate as lead_inquiry_sell_by_date,
leadinquirysource as lead_inquiry_source,
leadinquirytypeofinformationrequested as lead_inquiry_type_of_information_requested,
--leadproductdimkey as lead_product_dim_key,
lower(leadproductname) as lead_product_name,
--leadreasondimkey as lead_reason_dim_key,
leadrecipientproddetail as lead_recipient_prod_detail,
leadrecipientprodfamily as lead_recipient_prod_family,
lower(leadstatusdescription) as lead_status_description,
--leadstatusdimkey as lead_status_dim_key,
leadstatusid as lead_status_id,
--leadsystemdimkey as lead_system_dim_key,
lower(leadtypedescription) as lead_type_description,
--leadtypedimkey as lead_type_dim_key,
leadtypeid as lead_type_id,
listingagentagentid as listing_agent_party_id,
--listingagentdimkey as listing_agent_dim_key,
listingagentlegacycustid as listing_agent_legacy_cust_id,
listingagentsalesforceaccountid as listing_agent_salesforce_account_id,
--listingbrokerdimkey as listing_broker_dim_key,
listingbrokerid as listing_broker_party_id,
listingbrokerlegacyfirmid as listing_broker_legacy_firm_id,
listingbrokersalesforceaccountid as listing_broker_salesforce_account_id,
listingdimkey as listing_dim_key,
case when listingdimlistingid='-1' then listingid else listingdimlistingid end as listing_id,
--listingmsadimkey as listing_msa_dim_key,
--listingofficedimkey as listing_office_dim_key,
--listingofficelegacycustid as listing_office_legacy_cust_id,
listingofficeofficeid as listing_office_party_id,
listingofficesalesforceaccountid as listing_office_salesforce_account_id,
listingofficesiebelacctid as listing_office_siebel_acct_id,
listingpostalcode as listing_postal_code,
--listingrefid as listing_ref_id,
market,
markettype as market_type,
masterplanid as master_plan_id,
modifieddatetime as modified_datetime,
mprid as mpr_id,
msa,
msaid as msa_id,
msaminor as msa_minor,
msaminordescription as  msa_minor_description,
msaminorid as msa_minor_id,
lead_submit_date_mst as mst_lead_submit_date,
mstleadsubmitdate as mst_lead_submit_date_id,
mstleadsubmitdatetime as mst_lead_submit_datetime,
case when officecustid in ('NA', '-1', '0', '') then officecustomerlegacycustid else officecustid end as office_cust_id,
officecustomercustomerid as office_party_id,
--officecustomerdimkey as office_customer_dim_key,
--officecustomerlegacycustid as office_customer_legacy_cust_id,
officecustomersalesforceaccountid as office_salesforce_account_id,
orderid as order_id,
pagecategory as page_category,
--pagedimkey as page_dim_key,
pagename as page_name,
pagesubcategory as page_subcategory,
pagetemplate as page_template,
pagevariation as page_variation,
--placeonthepagedimkey as place_on_the_page_dim_key,
--plandimkey as plan_dim_key,
customerleadtypedescription as paid_type,
customerleadtypegroup as paid_type_group,
plannumber as plan_number,
--porch_lead_porch_report_success_datetime,
--porch_lead_sent_to_porch_datetime,
--porchleaddeliverystatusdeliverystatus,
--porchleaddimkey,
--porchleadleadid,
--porchleadporchoptinflag,
--porchleadporchreportsuccessdatetime,
--porchleadsenttoporchdatetime,
--pricebucketdimkey as price_bucket_dim_key,
pricebucketname as price_bucket_name,
pricegroupname as price_group_name,
--productsetdimkey as product_set_dim_key,
productsetid as product_set_id,
productsetname as product_set_name,
propertydimkey as property_dim_key,
propertyid as property_id,
propertypostalcode as property_postal_code,
propertyuspsgeographydimkey as property_usps_geography_dim_key,
rdcfulfillmentproductbitmaskid as rdc_fulfillment_product_bitmask_id,
CASE WHEN rdcfulfillmentproductbitmaskid & 128 = 128 THEN 'Agent Showcase'
WHEN ( rdcfulfillmentproductbitmaskid & 8388608 = 8388608
OR rdcfulfillmentproductbitmaskid & 256 = 256
OR rdcfulfillmentproductbitmaskid & 2048 = 2048
) THEN 'Office Showcase'
WHEN rdcfulfillmentproductbitmaskid & 64 = 64 THEN 'Office Standard'
WHEN hascobroke = 1 THEN 'Co-Broke'
WHEN ( rdcfulfillmentproductbitmaskid IS NULL
OR (
rdcfulfillmentproductbitmaskid & 128 <> 128
AND rdcfulfillmentproductbitmaskid & 8388608 <> 8388608
AND rdcfulfillmentproductbitmaskid & 256 <> 256
AND rdcfulfillmentproductbitmaskid & 2048 <> 2048
AND rdcfulfillmentproductbitmaskid & 64 <> 64
) ) THEN 'Agent Basic' end as rdc_fulfillment_product_bitmask_description,
rdcfulfillmentproductdescription as rdc_fulfillment_product_description,
--rdcfulfillmentproductdimkey as rdc_fulfillment_product_dim_key,
rdcfulfillmentproductgroup as rdc_fulfillment_product_group,
rdcfulfillmentproductname as rdc_fulfillment_product_name,
advertiserid as recipient_advertiser_id,
--recipientcustomerdimkey as recipient_customer_dim_key,
--recipientcustomerid as recipient_customer_id,
--recipientcustomerlegacycustid as recipient_customer_legacy_cust_id,
lower(contactmethod) as recipient_contact_method,
contactvalue as recipient_contact_value,
recipientcustomername as recipient_customer_name,
recipientcustomeroffice as recipient_customer_office,
recipientcustomertype as recipient_customer_type,
leadrecipientcustomerid as recipient_party_id,
case when recipientcustomersalesforceaccountid in ('NA', '')
then case when recipientcustomerid like '0%'
then
recipientcustomerid end else recipientcustomersalesforceaccountid end as recipient_salesforce_account_id,
case when recipientcustomerid like '1-%'
then
recipientcustomerid end as recipient_siebel_account_id,
--recipientcustomersalesforceaccountid as recipient_enterprise_account_id,
lower(recipientstatusdescription) as recipient_status_description,
refelementdescription as ref_element_description,
--refelementdimkey as ref_element_dim_key,
refelementname as ref_element_name,
--referringverticaldimkey as referring_vertical_dim_key,
--referringverticalname as referring_vertical_name,
reportexperience as report_experience,
reportsourceapplicationname as report_source_application_name,
slotdetailsid as slot_details_id,
--sourceapplicationdimkey as source_application_dim_key,
sourceapplicationname as source_application_name,
--sourcebranddimkey as source_brand_dim_key,
sourcebrandname as source_brand_name,
memberaccountid as source_consumer_member_id,
sessionid as source_consumer_session_id,
visitorid as source_consumer_visitor_id,
leadcategory as source_lead_category,
--leadcategorydimkey as lead_category_dim_key,
leadcategorygroup as source_lead_category_group,
leadcategorysemigroup as source_lead_category_semi_group,
leadcategorysubgroup as source_lead_category_subgroup,
leadid as source_lead_id,
sourcesectionname as source_section_name,
submittedleadid as source_submitted_lead_id,
sourcesubsectionname as source_subsection_name,
sourcesystemdescription as source_system_description,
sourcesystemid as source_system_id,
sourceversion as source_version,
sourcewidgetname as source_widget_name,
--subdivisiondimkey as subdivision_dim_key,
subdivisionname as subdivision_name,
subdivisionnumber as subdivision_number,
submittedleadcount as submitted_lead_count,
lower(submittedleadid) as submitted_lead_id,
--tigerleadmessage,
--tigerleadreasoncode,
--tigerleadreasondimkey,
--tigerleadstatus,
timedimkey as time_dim_key,
timeofday as time_of_day,
tollfreenumber as toll_free_number,
--turbocampaignid as turbo_campaign_id,
widgetdimkey as widget_dim_key,
widgetoption1 as widget_option1,
widgetoption2 as widget_option2,
--xleadsbillingcustomerid as xleads_billing_customer_id,
mstleadsubmitdate as mst_submit_date
--lpad(year, 4, '0') as year,
--lpad(month, 2, '0') as month,
--lpad(day, 2, '0') as day
from
(select
listingdimlistingid, listingid, hascobroke, customerleadtypegroup, contactphone, billingadvertiserid,
mstleadsubmitdate,leadid,slotdetailsid,leadinquirysearchcriteriaaddress,
connectedagentcustomerid,leadcontactdimkey,agentofficeid,agentcustomerid,
porchleadporchreportsuccessdatetime,rdcfulfillmentproductname,leadcount,leadcontactmethod,leadidxleads,connectedagentcustomerdimkey,leadinquiryestimatedtimeframe,agentsalesforceaccountid,connectedagentcustomerlegacycustid,timedimkey,billingcustomerid,leadcontactmethodgroup,recipientcustomerid,communityid,turbocampaignid,freeleadreason,leadtypedescription,subdivisiondimkey,sourcesystemid,leadinquirypreferredresponsetime,submittedleadid,productsetname,pagesubcategory,contactfullname,advertiserselectedcount,leadinquiryemailcopytoself,leadproductname,sourceapplicationname,recipientcustomersalesforceaccountid,pricebucketname,mstleadsubmitdatetime,refelementdimkey,leadcategorydimkey,leadtypeid,widgetdimkey,datasourcedimkey,contactmethod,customerleadtypedimkey,brokersalesforceaccountid,bopcode,productsetdimkey,recipientcustomeroffice,referringverticalname,visitorid,sourcesystemdescription,eventattributesgroupbitmask,billinglegacycustid,pagetemplate,porchleadleadid,officecustomerdimkey,listingbrokersalesforceaccountid,xleadsbillingcustomerid,leadadvertisertype,conlistingproductrecipientcustcustomerid,listingofficesiebelacctid,billingcustid,leadinquirysource,channelclassification,sourceapplicationdimkey,agentofficedimkey,agentcustomerdimkey,porchleaddeliverystatusdeliverystatus,sourceversion,leadcategorysubgroup,porchleadsenttoporchdatetime,subdivisionname,sourcebranddimkey,duplicateleadid,duration,leadproductdimkey,channelname,callresponsedimkey,agentlegacycustid,pagecategory,leadsystemdimkey,connectedagentadvid,leadinquirytypeofinformationrequested,fcmasource,blockedleadreason,contactemail,eventtypeid,bdxplanid,recipientcustomertype,officecustomercustomerid,msaminorid,msaminor,recipientcustomerlegacycustid,refelementdescription,leadadvertiserselectiontypedimkey,plandimkey,leadinquirysearchcriteriastate,porchleadporchoptinflag,fcmapricemax,leadstatusdimkey,fcmapricemin,productsetid,widgetoption2,gatewaydimkey,leadreasondimkey,gatewayname,leadinquirydimkey,sourcebrandname,leadadvertiserselectiontype,leadtypedimkey,listingagentdimkey,connectedagentcustomersalesforceaccountid,billtoproductid,listingagentlegacycustid,markettype,communitydimkey,listingofficesalesforceaccountid,agentofficelegacycustid,pagedimkey,recipientstatusdescription,consumeroperatingsystem,leadcategorygroup,submittedleadcount,leadstatusdescription,datasourceid,conlistingproductrecipientcustsalesforceaccountid,domaindimkey,officecustomersalesforceaccountid,leadcategorysemigroup,listingofficeofficeid,market,rdcfulfillmentproductgroup,propertyuspsgeographydimkey,tigerleadreasoncode,leadcontactmethoddimkey,contactaccountid,listingagentsalesforceaccountid,tigerleadstatus,billingcustomerdimkey,actualleadreceivercount,leadrecipientcustomerid,conproductrdcfulfillmentproductname,leadstatusid,leadformname,msa,leadrecipientproddetail,channeldimkey,listingid,leadinquirysearchcriteriapostalcode,consumermemberdimkey,propertypostalcode,brokerlegacycustid,leadinquirysearchcriteriacity,eventtypedimkey,placeonthepagedimkey,sessionid,communitymanagmentid,brokercustomerid,porchleaddimkey,leadinquirysavelisting,contactvalue,listingofficedimkey,consumerscreenwidth,agentofficesiebelacctid,msaid,rdcfulfillmentproductdescription,mprid,conlistingproductrecipientcustdimkey,bdxsubdivisionid,leadinquirylistingmlsnumber,brokeracctid,listingagentagentid,leadinquirysellbydate,rdcfulfillmentproductdimkey,leadrecipientprodfamily,masterplanid,propertyid,sourcesubsectionname,tigerleadmessage,widgetoption1,conlistingproductrecipientcustlegacycustid,refelementname,fcma,fcmainquirydimkey,listingdimkey,freelead,domainname,listingmsadimkey,tollfreenumber,consumerdevicedetailsdimkey,leadforid,flexflag,officecustid,msaminordescription,sourcewidgetname,propertydimkey,leadinquiryquestionorcomment,agentofficesalesforceaccountid,officecustomerlegacycustid,leadformdimkey,listingbrokerid,leadcategory,billinglineitem,rdcfulfillmentproductbitmaskid,fcmabeds,fcmabaths,listingpostalcode,leadinquirypreferredcontacttime,memberaccountid,timeofday,billingsalesforceaccountid,tigerleadreasondimkey,billablecustomerid,recipientcustomername,listingbrokerlegacyfirmid,orderid,pricebucketdimkey,listingrefid,customerleadtypedescription,brokercustomerdimkey,listingofficelegacycustid,recipientcustomerdimkey,billtoproductdescription,brokercdhpartyid,billingrefernceid,sourcesectionname,consumerdevicetype,subdivisionnumber,eventattributesdimkey,bopbillingreferenceid,listingbrokerdimkey,advertiserid,referringverticaldimkey,conproductfullfillmentgroupdimkey,leadinquirysearchcriteriapropertytypes,leadinquiryrentalmovingdatetime,pagename,eventtypedescription,pricegroupname,plannumber,pagevariation,hour,createddatetime,modifieddatetime,reportexperience,reportsourceapplicationname,etl_ztg_id,etl_partition_key_timestamp,etl_create_date,etl_source_filename,etl_source_partition_timestamp,etl_datatype_processed_ind,etl_invalid_criticality_ind,etl_dedupe_md5_checksum,etl_rd_arrival_year,etl_rd_arrival_month,etl_rd_arrival_hour,etl_rd_arrival_day,lead_submit_date_mst,porch_lead_porch_report_success_datetime,porch_lead_sent_to_porch_datetime,lead_inquiry_rental_moving_datetime,
case when leadid<>'00000000-0000-0000-0000-000000000000' then concat('leadid-',leadid)
when leadidxleads<>'' then concat('leadidxleads-',leadidxleads)
when sessionid<>'' then concat('sessionid-', sessionid, '-listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid)
else concat('listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid) end etl_unique_lead_id,
year,month,day,
row_number() over (partition by case when leadid<>'00000000-0000-0000-0000-000000000000' then concat('leadid-',leadid)
when leadidxleads<>'' then concat('leadidxleads-',leadidxleads)
when sessionid<>'' then concat('sessionid-', sessionid, '-listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid)
else concat('listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid) end
order by etl_rd_arrival_year desc, etl_rd_arrival_month desc, etl_rd_arrival_day desc, etl_rd_arrival_hour desc) dedupe_num
from leads_edw_pdt.lead_transactional_fact
) business_dedupe
where dedupe_num = 1