    with business_dedupe as
    (select
listingdimlistingid, listingid, hascobroke, customerleadtypegroup, contactphone, billingadvertiserid,
mstleadsubmitdate,leadid,slotdetailsid,leadinquirysearchcriteriaaddress,
connectedagentcustomerid,leadcontactdimkey,agentofficeid,agentcustomerid,
porchleadporchreportsuccessdatetime,rdcfulfillmentproductname,leadcount,leadcontactmethod,leadidxleads,connectedagentcustomerdimkey,leadinquiryestimatedtimeframe,agentsalesforceaccountid,connectedagentcustomerlegacycustid,timedimkey,billingcustomerid,leadcontactmethodgroup,recipientcustomerid,communityid,turbocampaignid,freeleadreason,leadtypedescription,subdivisiondimkey,sourcesystemid,leadinquirypreferredresponsetime,submittedleadid,productsetname,pagesubcategory,contactfullname,advertiserselectedcount,leadinquiryemailcopytoself,leadproductname,sourceapplicationname,recipientcustomersalesforceaccountid,pricebucketname,mstleadsubmitdatetime,refelementdimkey,leadcategorydimkey,leadtypeid,widgetdimkey,datasourcedimkey,contactmethod,customerleadtypedimkey,brokersalesforceaccountid,bopcode,productsetdimkey,recipientcustomeroffice,referringverticalname,visitorid,sourcesystemdescription,eventattributesgroupbitmask,billinglegacycustid,pagetemplate,porchleadleadid,officecustomerdimkey,listingbrokersalesforceaccountid,xleadsbillingcustomerid,leadadvertisertype,conlistingproductrecipientcustcustomerid,listingofficesiebelacctid,billingcustid,leadinquirysource,channelclassification,sourceapplicationdimkey,agentofficedimkey,agentcustomerdimkey,porchleaddeliverystatusdeliverystatus,sourceversion,leadcategorysubgroup,porchleadsenttoporchdatetime,subdivisionname,sourcebranddimkey,duplicateleadid,duration,leadproductdimkey,channelname,callresponsedimkey,agentlegacycustid,pagecategory,leadsystemdimkey,connectedagentadvid,leadinquirytypeofinformationrequested,fcmasource,blockedleadreason,contactemail,eventtypeid,bdxplanid,recipientcustomertype,officecustomercustomerid,msaminorid,msaminor,recipientcustomerlegacycustid,refelementdescription,leadadvertiserselectiontypedimkey,plandimkey,leadinquirysearchcriteriastate,porchleadporchoptinflag,fcmapricemax,leadstatusdimkey,fcmapricemin,productsetid,widgetoption2,gatewaydimkey,leadreasondimkey,gatewayname,leadinquirydimkey,sourcebrandname,leadadvertiserselectiontype,leadtypedimkey,listingagentdimkey,connectedagentcustomersalesforceaccountid,billtoproductid,listingagentlegacycustid,markettype,communitydimkey,listingofficesalesforceaccountid,agentofficelegacycustid,pagedimkey,recipientstatusdescription,consumeroperatingsystem,leadcategorygroup,submittedleadcount,leadstatusdescription,datasourceid,conlistingproductrecipientcustsalesforceaccountid,domaindimkey,officecustomersalesforceaccountid,leadcategorysemigroup,listingofficeofficeid,market,rdcfulfillmentproductgroup,propertyuspsgeographydimkey,tigerleadreasoncode,leadcontactmethoddimkey,contactaccountid,listingagentsalesforceaccountid,tigerleadstatus,billingcustomerdimkey,actualleadreceivercount,leadrecipientcustomerid,conproductrdcfulfillmentproductname,leadstatusid,leadformname,msa,leadrecipientproddetail,channeldimkey,listingid,leadinquirysearchcriteriapostalcode,consumermemberdimkey,propertypostalcode,brokerlegacycustid,leadinquirysearchcriteriacity,eventtypedimkey,placeonthepagedimkey,sessionid,communitymanagmentid,brokercustomerid,porchleaddimkey,leadinquirysavelisting,contactvalue,listingofficedimkey,consumerscreenwidth,agentofficesiebelacctid,msaid,rdcfulfillmentproductdescription,mprid,conlistingproductrecipientcustdimkey,bdxsubdivisionid,leadinquirylistingmlsnumber,brokeracctid,listingagentagentid,leadinquirysellbydate,rdcfulfillmentproductdimkey,leadrecipientprodfamily,masterplanid,propertyid,sourcesubsectionname,tigerleadmessage,widgetoption1,conlistingproductrecipientcustlegacycustid,refelementname,fcma,fcmainquirydimkey,listingdimkey,freelead,domainname,listingmsadimkey,tollfreenumber,consumerdevicedetailsdimkey,leadforid,flexflag,officecustid,msaminordescription,sourcewidgetname,propertydimkey,leadinquiryquestionorcomment,agentofficesalesforceaccountid,officecustomerlegacycustid,leadformdimkey,listingbrokerid,leadcategory,billinglineitem,rdcfulfillmentproductbitmaskid,fcmabeds,fcmabaths,listingpostalcode,leadinquirypreferredcontacttime,memberaccountid,timeofday,billingsalesforceaccountid,tigerleadreasondimkey,billablecustomerid,recipientcustomername,listingbrokerlegacyfirmid,orderid,pricebucketdimkey,listingrefid,customerleadtypedescription,brokercustomerdimkey,listingofficelegacycustid,recipientcustomerdimkey,billtoproductdescription,brokercdhpartyid,billingrefernceid,sourcesectionname,consumerdevicetype,subdivisionnumber,eventattributesdimkey,bopbillingreferenceid,listingbrokerdimkey,advertiserid,referringverticaldimkey,conproductfullfillmentgroupdimkey,leadinquirysearchcriteriapropertytypes,leadinquiryrentalmovingdatetime,pagename,eventtypedescription,pricegroupname,plannumber,pagevariation,hour,createddatetime,modifieddatetime,reportexperience,reportsourceapplicationname,etl_ztg_id,etl_partition_key_timestamp,etl_create_date,etl_source_filename,etl_source_partition_timestamp,etl_datatype_processed_ind,etl_invalid_criticality_ind,etl_dedupe_md5_checksum,etl_rd_arrival_year,etl_rd_arrival_month,etl_rd_arrival_hour,etl_rd_arrival_day,lead_submit_date_mst,porch_lead_porch_report_success_datetime,porch_lead_sent_to_porch_datetime,lead_inquiry_rental_moving_datetime,
case when leadid<>'00000000-0000-0000-0000-000000000000' then concat('leadid-',leadid)
when leadidxleads<>'' then concat('leadidxleads-',leadidxleads)
when sessionid<>'' then concat('sessionid-', sessionid, '-listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid)
else concat('listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid) end etl_unique_lead_id,
year,month,day,
row_number() over (partition by case when leadid<>'00000000-0000-0000-0000-000000000000' then concat('leadid-',leadid)
when leadidxleads<>'' then concat('leadidxleads-',leadidxleads)
when sessionid<>'' then concat('sessionid-', sessionid, '-listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid)
else concat('listingid-', listingid, '-advertiserid-', advertiserid, '-contactvalue-', contactvalue, '-listingagentagentid-', listingagentagentid, '-listingofficeofficeid-', listingofficeofficeid) end
order by etl_rd_arrival_year desc, etl_rd_arrival_month desc, etl_rd_arrival_day desc, etl_rd_arrival_hour desc) dedupe_num
from lead_transactional_fact
<where_partition_clause>
)
insert overwrite table leads
partition(mst_submit_date)
    select
actualleadreceivercount as actual_lead_receiver_count,
advertiserselectedcount as advertiser_selected_count,
agentofficeid as agent_office_party_id,
agentofficesalesforceaccountid as agent_office_salesforce_account_id,
agentofficesiebelacctid as agent_office_siebel_acct_id,
agentcustomerid as agent_party_id,
agentsalesforceaccountid as agent_salesforce_account_id,
bdxplanid as bdx_plan_id,
bdxsubdivisionid as bdx_subdivision_id,
lower(billtoproductdescription) as bill_to_product_description,
billtoproductid as bill_to_productid,
billingadvertiserid as billing_advertiser_id,
billingcustomerid as billing_customer_id,
billingsalesforceaccountid as billing_enterprise_account_id,
billinglineitem as billing_line_item,
billingcustid as billing_party_id,
billingrefernceid as billing_reference_id,
lower(blockedleadreason) as blocked_lead_reason,
bopbillingreferenceid as bop_billing_reference_id,
bopcode as bop_code,
case when brokercustomerid='-1' then brokercdhpartyid else brokercustomerid end as broker_party_id,
case when brokersalesforceaccountid like '0%' then brokersalesforceaccountid when brokeracctid like '0%' then brokeracctid else '' end as broker_salesforce_account_id,
case when brokeracctid like '1-%' then brokeracctid when brokersalesforceaccountid like '1-%' then brokersalesforceaccountid else '' end as broker_siebel_account_id,
lower(channelclassification) as channel_classification,
lower(channelname) as channel_name,
communitydimkey as community_dim_key,
communityid as community_id,
communitymanagmentid as community_management_id,
conproductfullfillmentgroupdimkey as con_product_fullfillment_group_dim_key,
lower(conproductrdcfulfillmentproductname) as con_product_rdc_fulfillment_product_name,
contactaccountid as contact_account_id,
contactemail as consumer_contact_email,
contactfullname as consumer_contact_full_name,
lower(leadcontactmethod) as consumer_contact_method,
lower(leadcontactmethodgroup) as consumer_contact_method_group,
contactphone as consumer_contact_phone,
lower(memberaccountid) as consumer_member_id,
memberaccountid as consumer_member_id_raw,
lower(sessionid) as consumer_session_id,
sessionid as consumer_session_id_raw,
lower(visitorid) as consumer_visitor_id,
visitorid as consumer_visitor_id_raw,
createddatetime as created_datetime,
lower(domainname) as domain_name,
duplicateleadid as duplicate_lead_id,
duration as call_duration,
etl_unique_lead_id,
etl_ztg_id,
lower(eventtypedescription) as event_type_description,
eventtypeid as event_type_id,
flexflag as flex_flag,
lower(freeleadreason) as free_lead_reason,
lower(gatewayname) as gateway_name,
case when freelead=1 then 'y' else 'n' end as is_free_lead,
lower(leadadvertiserselectiontype) as lead_advertiser_selection_type,
lower(leadadvertisertype) as lead_advertiser_type,
lower(leadcategory) as lead_category,
leadcategory as lead_category_raw,
lower(leadcategorygroup) as lead_category_group,
leadcategorygroup as lead_category_group_raw,
lower(leadcategorysemigroup) as lead_category_semi_group,
leadcategorysemigroup as lead_category_semi_group_raw,
lower(leadcategorysubgroup) as lead_category_subgroup,
leadcategorysubgroup as lead_category_subgroup_raw,
leadcount as lead_count,
leadforid as lead_for_id,
lower(leadformname) as lead_form_name,
lower(leadid) as lead_id,
leadid as lead_id_raw,
leadidxleads as lead_id_xleads,
leadinquiryemailcopytoself as lead_inquiry_email_copy_to_self,
leadinquiryestimatedtimeframe as lead_inquiry_estimated_timeframe,
leadinquirylistingmlsnumber as lead_inquiry_listing_mls_number,
leadinquirypreferredcontacttime as lead_inquiry_preferred_contact_time,
leadinquirypreferredresponsetime as lead_inquiry_preferred_response_time,
leadinquiryquestionorcomment as lead_inquiry_question_or_comment,
lead_inquiry_rental_moving_datetime,
leadinquiryrentalmovingdatetime as lead_inquiry_rental_moving_datetime_str,
leadinquirysavelisting as lead_inquiry_save_listing,
leadinquirysearchcriteriaaddress as lead_inquiry_search_criteria_address,
leadinquirysearchcriteriacity as lead_inquiry_search_criteria_city,
leadinquirysearchcriteriapostalcode as lead_inquiry_search_criteria_postal_code,
leadinquirysearchcriteriapropertytypes as lead_inquiry_search_criteria_property_types,
leadinquirysearchcriteriastate as lead_inquiry_search_criteria_state,
leadinquirysellbydate as lead_inquiry_sell_by_date,
leadinquirysource as lead_inquiry_source,
leadinquirytypeofinformationrequested as lead_inquiry_type_of_information_requested,
lower(leadproductname) as lead_product_name,
lower(leadrecipientproddetail) as lead_recipient_prod_detail,
lower(leadrecipientprodfamily) as lead_recipient_prod_family,
lower(leadstatusdescription) as lead_status_description,
leadstatusid as lead_status_id,
lower(leadtypedescription) as lead_type_description,
leadtypeid as lead_type_id,
listingagentagentid as listing_agent_party_id,
listingagentlegacycustid as listing_agent_legacy_cust_id,
listingagentsalesforceaccountid as listing_agent_salesforce_account_id,
listingbrokerid as listing_broker_party_id,
listingbrokerlegacyfirmid as listing_broker_legacy_firm_id,
listingbrokersalesforceaccountid as listing_broker_salesforce_account_id,
listingdimkey as listing_dim_key,
case when listingdimlistingid='-1' then listingid else listingdimlistingid end as listing_id,
listingofficeofficeid as listing_office_party_id,
listingpostalcode as listing_postal_code,
lower(market) as market,
lower(markettype) as market_type,
masterplanid as master_plan_id,
modifieddatetime as modified_datetime,
mprid as mpr_id,
msa,
msaid as msa_id,
msaminor as msa_minor,
msaminordescription as  msa_minor_description,
msaminorid as msa_minor_id,
lead_submit_date_mst as mst_lead_submit_date,
mstleadsubmitdate as mst_lead_submit_date_id,
from_unixtime(unix_timestamp(mstleadsubmitdatetime, 'MM/dd/yyyy HH:mm:ss.SSS')) as mst_lead_submit_datetime,
mstleadsubmitdatetime as mst_lead_submit_datetime_str,
orderid as order_id,
lower(pagecategory) as page_category,
lower(pagename) as page_name,
lower(pagesubcategory) as page_subcategory,
lower(pagetemplate) as page_template,
lower(pagevariation) as page_variation,
lower(customerleadtypedescription) as paid_type,
lower(customerleadtypegroup) as paid_type_group,
plannumber as plan_number,
lower(pricebucketname) as price_bucket_name,
lower(pricegroupname) as price_group_name,
productsetid as product_set_id,
lower(productsetname) as product_set_name,
propertydimkey as property_dim_key,
propertyid as property_id,
propertypostalcode as property_postal_code,
propertyuspsgeographydimkey as property_usps_geography_dim_key,
rdcfulfillmentproductbitmaskid as rdc_fulfillment_product_bitmask_id,
lower(CASE WHEN rdcfulfillmentproductbitmaskid & 128 = 128 THEN 'Agent Showcase'
WHEN ( rdcfulfillmentproductbitmaskid & 8388608 = 8388608
OR rdcfulfillmentproductbitmaskid & 256 = 256
OR rdcfulfillmentproductbitmaskid & 2048 = 2048
) THEN 'Office Showcase'
WHEN rdcfulfillmentproductbitmaskid & 64 = 64 THEN 'Office Standard'
WHEN hascobroke = 1 THEN 'Co-Broke'
WHEN ( rdcfulfillmentproductbitmaskid IS NULL
OR (
rdcfulfillmentproductbitmaskid & 128 <> 128
AND rdcfulfillmentproductbitmaskid & 8388608 <> 8388608
AND rdcfulfillmentproductbitmaskid & 256 <> 256
AND rdcfulfillmentproductbitmaskid & 2048 <> 2048
AND rdcfulfillmentproductbitmaskid & 64 <> 64
) ) THEN 'Agent Basic' end) as rdc_fulfillment_product_bitmask_description,
lower(rdcfulfillmentproductdescription) as rdc_fulfillment_product_description,
lower(rdcfulfillmentproductgroup) as rdc_fulfillment_product_group,
lower(rdcfulfillmentproductname) as rdc_fulfillment_product_name,
advertiserid as recipient_advertiser_id,
lower(contactmethod) as recipient_contact_method,
contactvalue as recipient_contact_value,
recipientcustomername as recipient_customer_name,
recipientcustomeroffice as recipient_customer_office,
lower(recipientcustomertype) as recipient_customer_type,
leadrecipientcustomerid as recipient_party_id,
case when recipientcustomersalesforceaccountid in ('NA', '')
then case when recipientcustomerid like '0%'
then
recipientcustomerid end else recipientcustomersalesforceaccountid end as recipient_salesforce_account_id,
case when recipientcustomerid like '1-%'
then
recipientcustomerid end as recipient_siebel_account_id,
lower(recipientstatusdescription) as recipient_status_description,
lower(refelementdescription) as ref_element_description,
lower(refelementname) as ref_element_name,
lower(reportexperience) as report_experience,
lower(reportsourceapplicationname) as report_source_application_name,
slotdetailsid as slot_details_id,
lower(sourceapplicationname) as source_application_name,
lower(sourcebrandname) as source_brand_name,
lower(sourcesectionname) as source_section_name,
lower(sourcesubsectionname) as source_subsection_name,
lower(sourcesystemdescription) as source_system_description,
sourcesystemid as source_system_id,
sourceversion as source_version,
lower(sourcewidgetname) as source_widget_name,
lower(subdivisionname) as subdivision_name,
lower(subdivisionnumber) as subdivision_number,
submittedleadcount as submitted_lead_count,
lower(submittedleadid) as submitted_lead_id,
submittedleadid as submitted_lead_id_raw,
timedimkey as time_dim_key,
timeofday as time_of_day,
tollfreenumber as toll_free_number,
widgetdimkey as widget_dim_key,
lower(widgetoption1) as widget_option1,
lower(widgetoption2) as widget_option2,
mstleadsubmitdate as mst_submit_date
from
 business_dedupe
where dedupe_num = 1