WITH cntr_sfdc_products AS
(
select
row_number() OVER (PARTITION BY id ORDER BY CAST(systemmodstamp AS timestamp) DESC ) AS row_number_seq,
auto_renewal__c,
bigmachines__part_number__c,
charge_type__c,
commission_category__c,
createddate_mst,
default_term__c,
defaultrenewalterm__c,
dependent_part__c,
division__c,
family,
fulfillment_id__c,
fulfillment_required__c,
fulfillment_type__c,
id,
inventory__c,
inventory_description__c,
is_cfbc__c,
isactive,
isdeleted,
lastmodifieddate_mst,
lastreferenceddate_mst,
name,
normalization_factor__c,
pricing_method__c,
productcode,
renewal_term_type__c,
s_no__c,
subscription_type__c,
systemmodstamp,
tax_category__c
from
cntr_contract_pdt__es_dm_sfdc_product_vw
)
SELECT
cntr_sfdc_products.auto_renewal__c auto_renewal ,
cntr_sfdc_products.bigmachines__part_number__c big_machines_part_number ,
cntr_sfdc_products.charge_type__c charge_type ,
cntr_sfdc_products.commission_category__c commission_category ,
cntr_sfdc_products.createddate_mst created_date ,
cntr_sfdc_products.default_term__c default_term ,
cntr_sfdc_products.defaultrenewalterm__c default_renewal_term ,
cntr_sfdc_products.dependent_part__c description ,
cntr_sfdc_products.division__c division ,
cntr_sfdc_products.family family ,
cntr_sfdc_products.fulfillment_id__c fulfillment_id ,
cntr_sfdc_products.fulfillment_required__c fulfillment_required ,
cntr_sfdc_products.fulfillment_type__c fulfillment_type ,
cntr_sfdc_products.id product_id ,
cntr_sfdc_products.inventory__c inventory ,
cntr_sfdc_products.inventory_description__c inventory_description ,
CASE WHEN cntr_sfdc_products.is_cfbc__c = '1' THEN 'y' else 'n' END is_cfbc,
CASE WHEN cntr_sfdc_products.isactive = '1' THEN 'y' else 'n' END is_active,
CASE WHEN cntr_sfdc_products.isdeleted = '1' THEN 'y' else 'n' END is_deleted,
cntr_sfdc_products.lastmodifieddate_mst last_modified_date ,
cntr_sfdc_products.lastreferenceddate_mst last_referenced_date ,
cntr_sfdc_products.name product_name ,
cntr_sfdc_products.normalization_factor__c normalization_factor ,
cntr_sfdc_products.pricing_method__c pricing_method ,
cntr_sfdc_products.productcode product_code ,
cntr_sfdc_products.renewal_term_type__c renewal_term_type ,
cntr_sfdc_products.s_no__c s_no ,
cntr_sfdc_products.subscription_type__c subscription_type ,
cntr_sfdc_products.systemmodstamp systemmodstamp ,
cntr_sfdc_products.tax_category__c tax_category
FROM cntr_sfdc_products
WHERE cntr_sfdc_products.row_number_seq = 1
