WITH cntr_sfdc_accounts AS
(
select
row_number() OVER (PARTITION BY id ORDER BY CAST(systemmodstamp AS timestamp) DESC ) AS row_number_seq,
account_sub_type__c,
accountnumber,
advertiser_email__c,
advertiserid__c,
alerts__c,
associated_agent_account__c,
createdbyid,
createddate_mst,
credit_risk__c,
credit_status__c,
customer_id__c,
display_name__c,
division__c,
franchise_type__c,
grand_parent_account_id__c,
id,
lock_expiration_date__c,
lastmodifieddate_mst,
mls_set_id__c,
name,
next_renewal_date__c,
own_co_broke__c,
own_coshow__c,
own_cycle__c,
own_fac__c,
own_fcma__c,
own_fh__c,
own_fh_broke__c,
own_idx__c,
own_lh__c,
own_ms__c,
own_osl__c,
own_osr__c,
own_sle__c,
own_tiger__c,
own_tp_crm__c,
ownerid,
parent_broker__c,
party_id__c,
photourl,
price_list__c,
primary_clc__c,
primary_email__c,
primary_hlc__c,
sales_lock_user__c,
status__c,
status_as_of__c,
systemmodstamp,
territories__c,
total_agents__c,
total_clc__c,
total_contract_value__c,
total_hlc__c,
total_offices__c,
type,
website
from
cntr_contract_pdt__es_dm_sfdc_account_vw
)
SELECT
cntr_sfdc_accounts.account_sub_type__c account_sub_type ,
cntr_sfdc_accounts.accountnumber account_number ,
cntr_sfdc_accounts.advertiser_email__c advertiser_email,
cntr_sfdc_accounts.advertiserid__c advertiser_id,
cntr_sfdc_accounts.alerts__c alerts ,
cntr_sfdc_accounts.associated_agent_account__c associated_agent_account_id ,
cntr_sfdc_accounts.createdbyid created_by ,
cntr_sfdc_accounts.createddate_mst created_date ,
cntr_sfdc_accounts.credit_risk__c credit_risk ,
cntr_sfdc_accounts.credit_status__c credit_status ,
cntr_sfdc_accounts.customer_id__c billing_customer_id ,
cntr_sfdc_accounts.display_name__c display_name ,
cntr_sfdc_accounts.division__c division ,
cntr_sfdc_accounts.franchise_type__c franchise_type ,
cntr_sfdc_accounts.grand_parent_account_id__c grand_parent_account_id ,
cntr_sfdc_accounts.id account_id ,
cntr_sfdc_accounts.lastmodifieddate_mst last_modified_date ,
cntr_sfdc_accounts.lock_expiration_date__c lock_expiration_date ,
cntr_sfdc_accounts.mls_set_id__c mls_set_id ,
cntr_sfdc_accounts.name account_name ,
cntr_sfdc_accounts.next_renewal_date__c next_renewal_date ,
cntr_sfdc_accounts.own_co_broke__c own_co_broke ,
cntr_sfdc_accounts.own_coshow__c own_coshow ,
cntr_sfdc_accounts.own_cycle__c own_cycle ,
cntr_sfdc_accounts.own_fac__c own_fac ,
cntr_sfdc_accounts.own_fcma__c own_fcma ,
cntr_sfdc_accounts.own_fh__c own_fh ,
cntr_sfdc_accounts.own_fh_broke__c own_fh_broke ,
cntr_sfdc_accounts.own_idx__c own_idx ,
cntr_sfdc_accounts.own_lh__c own_lh ,
cntr_sfdc_accounts.own_ms__c own_ms ,
cntr_sfdc_accounts.own_osl__c own_osl ,
cntr_sfdc_accounts.own_osr__c own_osr ,
cntr_sfdc_accounts.own_sle__c own_sle ,
cntr_sfdc_accounts.own_tiger__c own_tiger ,
cntr_sfdc_accounts.own_tp_crm__c own_tp_crm ,
cntr_sfdc_accounts.ownerid account_owner_id ,
cntr_sfdc_accounts.parent_broker__c parent_broker ,
cntr_sfdc_accounts.party_id__c cdh_party_id ,
cntr_sfdc_accounts.photourl photo_url ,
cntr_sfdc_accounts.price_list__c price_list ,
cntr_sfdc_accounts.primary_clc__c primary_clc ,
cntr_sfdc_accounts.primary_email__c primary_email ,
cntr_sfdc_accounts.primary_hlc__c primary_hlc ,
cntr_sfdc_accounts.sales_lock_user__c sales_lock ,
cntr_sfdc_accounts.status__c status ,
cntr_sfdc_accounts.status_as_of__c status_as_of ,
CAST(cntr_sfdc_accounts.systemmodstamp AS timestamp)systemmodstamp ,
cntr_sfdc_accounts.territories__c territories ,
cntr_sfdc_accounts.total_agents__c total_agents ,
cntr_sfdc_accounts.total_clc__c total_clc ,
cntr_sfdc_accounts.total_contract_value__c total_contract_value ,
cntr_sfdc_accounts.total_hlc__c total_hlc ,
cntr_sfdc_accounts.total_offices__c total_offices ,
cntr_sfdc_accounts.type account_type ,
cntr_sfdc_accounts.website website_url
FROM cntr_sfdc_accounts
WHERE cntr_sfdc_accounts.row_number_seq = 1
