#!/usr/bin/env bash
aws s3 ls s3://move-dataeng-leads-dev/edw/business-data/lead10/



spark-submit --conf spark.hadoop.yarn.resourcemanager.connect.max-wait.ms=60000 --conf spark.hadoop.fs.defaultFS=hdfs://ip-172-31-50-173.us-west-2.compute.internal:8020 --conf spark.hadoop.yarn.resourcemanager.address=ip-172-31-50-173.us-west-2.compute.internal:8032 --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.minExecutors=1 --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.executor.memory=5g --conf spark.executor.cores=4 --name tape --master yarn --deploy-mode cluster --jars /opt/amazon/superjar/glue-assembly.jar --files /tmp/glue-default.conf,/tmp/glue-override.conf,/opt/amazon/certs/InternalAndExternalAndAWSTrustStore.jks,/opt/amazon/certs/rds-combined-ca-bundle.pem,/opt/amazon/certs/redshift-ssl-ca-cert.pem,/tmp/g-005146790883b729584b61466da5a58c866ee86c-8230443568287916864/script_2018-03-02-22-36-41.py --py-files /tmp/PyGlue.zip --driver-memory 5g --executor-memory 5g /tmp/runscript.py script_2018-03-02-22-36-41.py --JOB_NAME leads --JOB_ID j_13aa3a4579dd5e4d83a7b9b223effce1050239e406b1f3168b97a0ef7f8e4f81 --sql_param_variables [{"<where_partition_clause>":""}] --block_size_MB default --data_frame_sources [{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned": true,"s3_source_path": "s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}] --job_name leads --JOB_RUN_ID jr_e5266cf58415ff7d09dabee54e7fbd4c43f57c1955947393e9d510f431be5b8a --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads/ --source_sql_file_path ["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]


spark-submit --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.minExecutors=1 --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.executor.memory=5g --conf spark.executor.cores=4 --name tape --master yarn --deploy-mode cluster --files /tmp/glue-default.conf,/tmp/glue-override.conf,/opt/amazon/certs/InternalAndExternalAndAWSTrustStore.jks,/opt/amazon/certs/rds-combined-ca-bundle.pem,/opt/amazon/certs/redshift-ssl-ca-cert.pem,/tmp/g-005146790883b729584b61466da5a58c866ee86c-8230443568287916864/script_2018-03-02-22-36-41.py --py-files /tmp/PyGlue.zip --driver-memory 5g --executor-memory 5g /tmp/runscript.py script_2018-03-02-22-36-41.py --JOB_NAME leads --JOB_ID j_13aa3a4579dd5e4d83a7b9b223effce1050239e406b1f3168b97a0ef7f8e4f81 --sql_param_variables [{"<where_partition_clause>":""}] --block_size_MB default --data_frame_sources [{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned": true,"s3_source_path": "s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}] --job_name leads --JOB_RUN_ID jr_e5266cf58415ff7d09dabee54e7fbd4c43f57c1955947393e9d510f431be5b8a --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads/ --source_sql_file_path ["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]


spark-submit --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.minExecutors=1 --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.executor.memory=5g --conf spark.executor.cores=4 --name tape --master yarn --deploy-mode cluster --files s3://move-dataeng-code-dev/business-data/lead_generic_data_refresh.py --driver-memory 5g --executor-memory 5g lead_generic_data_refresh.py --py-files https://s3.amazonaws.com/aws-glue-jes-prod-us-east-1-assets/etl/python/PyGlue.zip --JOB_NAME leads --sql_param_variables [{"<where_partition_clause>":""}] --block_size_MB default --data_frame_sources [{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned": true,"s3_source_path": "s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}] --job_name leads --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads11/ --source_sql_file_path ["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]


spark-submit --conf spark.dynamicAllocation.enabled=true --conf spark.shuffle.service.enabled=true --conf spark.dynamicAllocation.minExecutors=1 --conf spark.dynamicAllocation.maxExecutors=8 --conf spark.executor.memory=5g --conf spark.executor.cores=4 --name tape --master yarn --deploy-mode cluster --files s3://move-dataeng-code-dev/business-data/lead_generic_data_refresh.py --driver-memory 5g --executor-memory 5g lead_generic_data_refresh.py --py-files s3://aws-glue-jes-prod-us-east-1-assets/etl/python/PyGlue.zip --JOB_NAME leads --sql_param_variables [{"<where_partition_clause>":""}] --block_size_MB default --data_frame_sources [{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned": true,"s3_source_path": "s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}] --job_name leads --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads11/ --source_sql_file_path ["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]


python test_lead_arg.py --JOB_NAME leads --sql_param_variables '[{"<where_partition_clause>":""}]' --block_size_MB default --data_frame_sources '[{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned":true,"s3_source_path":"s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}]' --job_name leads --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads11/ --source_sql_file_path '["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]'


python test_lead_arg.py --JOB_NAME leads --sql_param_variables '[{"<where_partition_clause>":""}]'

python test_lead_arg.py --job_name leads --sql_param_variables '[{"<where_partition_clause>":"where (year=2018 and month=01 and day=02)"}]' --block_size_MB default --data_frame_sources '[{"source_file_type_parquet_or_text":"parquet","get_all_completed_partitions":"","temp_table_name":"lead_transactional_fact","app_id":"leads.edw.pdt.lead_transactional_fact","partition_by":["year","month","day"],"is_partitioned":true,"s3_source_path":"s3://move-dataeng-leads-prod/edw/processed-data-xact/lead_transactional_fact/"}]' --job_name leads --s3_target_path s3://move-dataeng-leads-dev/edw/business-data/leads11/ --source_sql_file_path '["s3://move-dataeng-code-dev/business-data/sql/leads_bd_drop_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_bd_create_external_table.sql","s3://move-dataeng-code-dev/business-data/sql/leads_business_dedupe_full.sql"]'

ssh -i <private-key.pem> glue@ec2-34-213-176-53.us-west-2.compute.amazonaws.com -t gluepyspark

ssh glue@ec2-34-213-176-53.us-west-2.compute.amazonaws.com -t gluepyspark

ssh -NTL 9007:169.254.76.1:9007 glue@ec2-34-213-176-53.us-west-2.compute.amazonaws.com