SELECT concat(coalesce(cast(ListingDimKey as varchar), '') ,'^',
coalesce(cast(ListingID as varchar), ''),'^',
coalesce(cast(UDBListingID as varchar), '') ,'^',
coalesce(cast(PropertyID as varchar), '') ,'^',
coalesce(ListingSourceAliasID, '') ,'^',
coalesce(ListingDataSourceID, '') ,'^',
coalesce(ListingAgentSourceAliasID, '') ,'^',
coalesce(ListingOfficeSourceAliasID, '') ,'^',
coalesce(ListingAgentOfficeDataSourceID, '') ,'^',
coalesce(ListingCoAgentSourceAliasID, '') ,'^',
coalesce(ListingCoOfficeSourceAliasID, '') ,'^',
coalesce(ListingCoAgentOfficeDataSourceID, '') ,'^',
coalesce(BuyerAgentSourceAliasID, '') ,'^',
coalesce(BuyerOfficeSourceAliasID, '') ,'^',
coalesce(BuyerAgentOfficeDataSourceID, '') ,'^',
coalesce(BuyerCoAgentSourceAliasID, '') ,'^',
coalesce(BuyerCoOfficeSourceAliasID, ''),'^',
coalesce(BuyerCoAgentOfficeDataSourceID, '') ,'^',
coalesce(cast(ListingOriginalPrice as varchar), '') ,'^',
coalesce(cast(ListingCurrentPrice as varchar), '') ,'^',
coalesce(cast(ListingRentalPrice as varchar), '') ,'^',
coalesce(cast(ListingType as varchar), '') ,'^',
coalesce(cast(case when IsRental then 1 else 0 end as varchar), '') ,'^',
coalesce(ListingAddress, '') ,'^',
coalesce(ListingCity, '') ,'^',
coalesce(ListingCounty, '') ,'^',
coalesce(ListingState, '') ,'^',
coalesce(ListingPostalCode, '') ,'^',
coalesce(cast(ListingGeoApproximation as varchar), '') ,'^',
coalesce(cast(ListingNumberOfBedrooms as varchar), '') ,'^',
coalesce(cast(ListingNumberOfBathrooms as varchar), '') ,'^',
coalesce(cast(ListingNumberOfStories as varchar), '') ,'^',
coalesce(ListingStyle, '') ,'^',
coalesce(cast(ListingSquareFeet as varchar), '') ,'^',
coalesce(cast(ListingLotSquareFeet as varchar), '') ,'^',
coalesce(ListingStatus, '') ,'^',
coalesce(ListingMarketingType, '') ,'^',
coalesce(cast(case when IsForeclosure then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(case when IsPriceDropped then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(case when IsPriceIncreased then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(ListingPriceIncreasedDate as varchar), '') ,'^',
coalesce(cast(ListingPriceReducedDate as varchar), '') ,'^',
coalesce(cast(date_format(ListingStartDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(date_format(ListingEndDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(FulfillmentGroupBitMask as varchar), '') ,'^',
coalesce(cast(EffectiveFrom as varchar), '')  ,'^',
coalesce(cast(EffectiveTo as varchar), '')  ,'^',
coalesce(ListingCountry, '') ,'^',
coalesce(cast(case when IsDisplayed then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(date_format(ListingSoldDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(ListingSoldPrice as varchar), '') ,'^',
coalesce(cast(case when IsAOLSyndication then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(case when IsRDCSyndication then 1 else 0 end as varchar), '') ,'^',
coalesce(PropertyDescription, '') ,'^',
coalesce(Headline, '')  ,'^',
coalesce(Headline2, '')  ,'^',
coalesce(SpecialMessage, '')  ,'^',
coalesce(cast(ListingPhotoCount as varchar), '') ,'^',
coalesce(cast(ListingPercentageCompleteness as varchar), '') ,'^',
coalesce(ListingProvider, '') ,'^',
coalesce(cast(CreatedDate as varchar), '') ,'^',
coalesce(CreatedBy, '') ,'^',
coalesce(cast(ModifiedDate as varchar), '') ,'^',
coalesce(ModifiedBy, '') ,'^',
coalesce(cast(case when IsVideo then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(case when IsVirtualTour then 1 else 0 end as varchar), '') ,'^',
coalesce(ListingPhotoURL, '') ,'^',
coalesce(cast(case when IsOpenHouse then 1 else 0 end as varchar), '') ,'^',
coalesce(cast(date_format(OpenHouseStartDate, 'MMM dd yyyy hh:mma') as varchar), '')  ,'^',
coalesce(cast(date_format(OpenHouseEndDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(date_format(ListingStatusChangedDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(date_format(SystemCreationDate, 'MMM dd yyyy hh:mma') as varchar), '') ,'^',
coalesce(cast(SpecID as varchar), '') ,'^',
coalesce(cast(MasterPlanID as varchar), '') ,'^',
coalesce(cast(HasCoBroke as varchar), '') ,'^',
coalesce(cast(HasCoBrokePhone as varchar), '') ,'^',
coalesce(cast(DAPendingFlag as varchar), '') ,'^',
coalesce(cast(DAPendingDate as varchar), '') ,'^',
coalesce(cast(NonMLSFlag as varchar), '') ,'^',
coalesce(cast(ProductTypeDimKey as varchar), '') ,'^',
coalesce(cast(IsChoiceEnabled as varchar), '') ,'^',
coalesce(ListingRawStatus, '') ,'^',
coalesce(cast(NewConstructionFlag as varchar), '')) as s3_data,
date_format(coalesce( ModifiedDate, CreatedDate), 'yyyy') as year,
date_format(coalesce( ModifiedDate, CreatedDate), 'MM') as month
 FROM
 movedm.edw_tbllistingdim_parquet
